version: "3.9"
services:
  model:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./models:/models
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - 8501:8501
    environment:
    - MODEL_HOST=model
